const burgeroptions = [
  {
    name: "Beef Patty",
    vegetarian: "no",
    calories: 204,
    part: "patty",
    img: "https://t3.ftcdn.net/jpg/02/68/56/90/360_F_268569020_l9W6h8HPatmfiqaUJo6Rdj2EMW9dAYim.jpg",
  },
  {
    name: "Fried Chicken",
    vegetarian: "no",
    calories: 210,
    part: "patty",
    img: "https://www.cfacdn.com/img/order/menu/Mobile/Entrees/Menu%20Item/CFAFilet_1080x1080.png",
  },
  {
    name: "Fried Tofu",
    vegetarian: "yes",
    calories: 149,
    part: "patty",
    img: "https://veganonboard.com/wp-content/uploads/2021/07/breaded-tofu-10.jpg",
  },
  {
    name: "Veggie Patty",
    vegetarian: "yes",
    calories: 124,
    part: "patty",
    img: "https://i0.wp.com/www.foodlovinfamily.com/wp-content/uploads/2021/05/Air-fryer-veggie-burgers.jpg",
  },
  {
    name: "Cheddar",
    vegetarian: "yes",
    calories: 113,
    part: "cheese",
    img: "https://cdn.shopify.com/s/files/1/0287/2377/3499/products/7-Year-1191.jpg?v=1624038493&width=1946",
  },
  {
    name: "Monterey Jack",
    vegetarian: "yes",
    calories: 106,
    part: "cheese",
    img: "https://store.pagelsponderosa.com/wp-content/uploads/2020/08/Monterey-Jack-Block-resized-scaled.jpg",
  },
  {
    name: "White Cheddar",
    vegetarian: "yes",
    calories: 80,
    part: "cheese",
    img: "https://www.murrayscheese.com/site/images/items/20550800000.0.jpg?resizeid=6&resizeh=300&resizew=300",
  },
  {
    name: "Mozzarella Cheese",
    vegetarian: "yes",
    calories: 78,
    part: "cheese",
    img: "https://m.media-amazon.com/images/I/51rjKowTudL.jpg",
  },
  {
    name: "Lettuce",
    vegetarian: "yes",
    calories: 3,
    part: "toppings",
    img: "https://cdn.britannica.com/77/170677-050-F7333D51/lettuce.jpg",
  },
  {
    name: "Tomato",
    vegetarian: "yes",
    calories: 8,
    part: "toppings",
    img: "https://m.economictimes.com/thumb/msid-95423731,width-1200,height-900,resizemode-4,imgsize-56196/tomatoes-canva.jpg",
  },
  {
    name: "Avocado",
    vegetarian: "yes",
    calories: 100,
    part: "toppings",
    img: "https://cdn.britannica.com/72/170772-050-D52BF8C2/Avocado-fruits.jpg",
  },
  {
    name: "Bacon",
    vegetarian: "no",
    calories: 86,
    part: "toppings",
    img: "https://healthyrecipesblogs.com/wp-content/uploads/2018/01/oven-bacon-featured.jpg",
  },
];

export { burgeroptions };
